# Generated by Django 3.2.19 on 2023-05-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0031_initial_content_locale"),
        ("pretalx_halfnarp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="event",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="event.event"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="preference",
            name="hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="preference",
            unique_together={("hash", "event")},
        ),
    ]
